version: '3.1'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  app:
    container_name: publify-web
    image: fagorym/publify-web:latest
    ports:
      - "3000:3000"
